### ISSUE TITLE
Thắc mắc

### ISSUE THREAD

**Issue by kawasemi2k1** [kawasemi2k1/prjTHCSDL#1]
https://github.com/kawasemi2k1/prjTHCSDL/blob/b505e662f4d6245642d93858b4d6f94fbf2cf248/src/OBJ/categories.java#L12

Sao object này không có thuộc tính gì à cậu? Chung xem lại file nhé.

**Comment by manhlamabc123** [comment]
Uk, chắc là như thế. (Đây là bản thử cho Thúy xem)

**Comment by kawasemi2k1** [comment]
cả brands nữa cậu ơi.
